spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Blog?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 11210904
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.lrm: info
  file:
    name: log/Blog-pro.log
server:
  port: 8081